### ISSUE TITLE
Using &attributes

### ISSUE THREAD

**Issue by Gooseware** [bluewings/pug-as-jsx-loader#3]
I was wondering if there was a way to pass objects into &attributes. As this would be really useful.

Thanks

**Comment by bluewings** [comment]
I tried to check the properties on the [example page](https://bluewings.github.io/pug-as-jsx-loader/), but it looks like it works fine as shown below.

Please let me know your use case and it will help me understand what you want.

![example](https://user-images.githubusercontent.com/1563202/31527906-359356dc-b00b-11e7-9733-b68f6bed4de5.png)

**Comment by bluewings** [comment]
Instead of using [&attributes](https://pugjs.org/language/attributes.html#attributes), you can use [JSX Spread Attributes](https://gist.github.com/sebmarkbage/07bbe37bc42b6d4aef81#spread-attributes).

In pure pugjs, non key-value expressions are not allowed. So I created a custom property called ```__jsx```. And you can use as follows.

![example2](https://user-images.githubusercontent.com/1563202/31530096-cf9a3fa4-b018-11e7-9ccd-62066a2fdfe2.png)
